### ISSUE TITLE
Doctor registration iteration3

### ISSUE THREAD

**Issue by MattKwak** [abegaz/mentcareSB#21]
Cannot register a new doctor using the .jar file for iteration3. either a button error or communication to database (banking on the later)

**Comment by Sarefx** [comment]
Its not working because database for Doctor was changed, so that version of the program is not gonna work.

**Comment by MattKwak** [comment]
should I be testing the version in the test branch in that case?

**Comment by Sarefx** [comment]
Test branch has bunch of unconnected code. I have latest copy with all additions. I will upload it soon, latest at the of today.
